from app.exceptions import AppError


class DrawError(AppError):
    pass
